### ISSUE TITLE
feature to include a comment with an entry

### ISSUE THREAD

**Issue by doubletwist13** [stjeanp/stjeanp-mail_aliases#1]
Just a 'nice to have' feature - It would be nice if there was a way to include a comment with a given entry. 

eg. [in hiera]

```
mail_alias:
  bob:
    recipient: 'somewhere@example.com'
    ensure: 'present'
    comment: 'This guy moved to Department Foo'
```

and have it show up in /etc/aliases as:

```
# This guy moved to Department Foo
bob: somewhere@example.com
```
